# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1dd5c34cc54b4bd607f8717e182d81064be630f46eb34f66449e6f05436be72f0ea7ff9ccab068bd59a494939d6b4af3767c0084aea96c3a4e0e49f7562b4f5

test:
  secret_key_base: 0da5964ba3c86ebec95057fa86f991adce9405268c3169e1e200edbba7f8c6da362cc86cd1bf2710c0796eb36269f26704f6f6585d6b072fae0bd8409b833206

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
